<?xml version="1.0"?>
<!DOCTYPE alumnos [
    <!ELEMENT alumno (nombre, nacimiento)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT nacimiento (#PCDATA)>
    <!ELEMENT alumnos (alumno +) >
]>
<alumno>
    <nombre>Eren Jaeger</nombre>
    <nacimiento>1835-03-30</nacimiento>
</alumno>
<alumno>
    <nombre>micasa acketman</nombre>
    <nacimiento>10/febrero/835</nacimiento>
</alumno>

<!DOCTYPE empleados [
    <!ELEMENT empleados (empleado+)>
    <!ELEMENT empleado (nombre, puesto, salario)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT puesto (#PCDATA)>
    <!ELEMENT salario (#PCDATA)>
]>

<empleados>
    <empleado>
        <nombre>Juan Pérez</nombre>
        <puesto>Gerente</puesto>
        <salario>5000</salario>
    </empleado>
    <empleado>
        <nombre>María Gómez</nombre>
        <puesto>Desarrolladora</puesto>
        <salario>4000</salario>
    </empleado>
</empleados>

<!DOCTYPE productos [
    <!ELEMENT productos (producto+)>
    <!ELEMENT producto (nombre, precio, categoria)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ELEMENT categoria (#PCDATA)>
]>

<productos>
    <producto>
        <nombre>Smartphone</nombre>
        <precio>300</precio>
        <categoria>Electrónica</categoria>
    </producto>
    <producto>
        <nombre>Lavadora</nombre>
        <precio>600</precio>
        <categoria>Electrodomésticos</categoria>
    </producto>
</productos>

<!DOCTYPE vehiculos [
    <!ELEMENT vehiculos (vehiculo+)>
    <!ELEMENT vehiculo (marca, modelo, año)>
    <!ELEMENT marca (#PCDATA)>
    <!ELEMENT modelo (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
]>

<vehiculos>
    <vehiculo>
        <marca>Toyota</marca>
        <modelo>Corolla</modelo>
        <año>2022</año>
    </vehiculo>
    <vehiculo>
        <marca>Ford</marca>
        <modelo>Focus</modelo>
        <año>2020</año>
    </vehiculo>
</vehiculos>
